Added jsonResponse field
testproject-io/addons pull request #11
Opened 2020-09-18 07:49 UTC by Rantzur1992

Added a jsonResponse field which will hold the output of the jsonPath query as a valid jsonObject.
Retained the current response as a string literal.

2020-09-18 13:25 UTC, mstrelex requested changes
@Rantzur1992 

- README.md update is missing, that should include an explanation about the new result field.
- Commit messages do not match actual changes - all the changes are in a single commit e037075e263ae577e8997fa9ea8619ce3a897575 and instead should be broken down to separate commits.

2020-09-18 13:25 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/base/BaseAction.java
>          response = (jsonPath.isEmpty()) ? serverResponse.responseBody : serverResponse.jsonParseResult;
You can check `jsonPath.isEmpty()` once and assign values accordingly, in if/else.

2020-09-18 13:25 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/internal/ReporterHelper.java
> +                resultStr.append("The value of \"").append(jsonPath).append("\" as JsonObject is \"").append(serverResponse.jsonParseResultAsJson).append("\". ").append(LS);
IMHO, it was a mistake to add quotes around the property value and the actual value in the first place.
In stead, we could put it in double curly brackets {{XXX}} and this would instruct the recorder / reports to make this portion of a text styled as bold.

Also, I would adda new line between these two result types, using `System.lineSeparator()`

2020-09-18 13:25 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/internal/RequestHelper.java
> +                    jsonPath,
Variable type and name should be on the same line.

2020-09-18 13:25 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/internal/RequestHelper.java
> +                        .hostnameVerifier((s, sslSession) -> true)
This change is absolutely not related to this PR, and should be submitted separately.

2020-09-18 13:25 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/internal/RequestHelper.java
> +                                    .jsonProvider(new GsonJsonProvider())
A comment here would be nice to explain why this is required and what it is doing.

2020-09-18 13:25 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/base/BaseAction.java
> +    @Parameter(description = "Value found using jsonPath specified (As JSON)", direction = ParameterDirection.OUTPUT)
```suggestion
    @Parameter(description = "Value found using jsonPath in a form of a JSON object", direction = ParameterDirection.OUTPUT)
```

2020-09-22 13:36 UTC, mstrelex requested changes

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/README.md
> +    The schema validation will work on the JSON response provided in the JsonResponse field.
```suggestion
    This parameter is for a *full** path of a local schema file, or a URL pointing to a remote schema file.
    If a URL is provided, it will download the schema locally to a temporary file, before performing the validation.
    Schema validation is performed on the JSON response object provided in the `JsonResponse` field.
```

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/README.md
> +* `createFile` - This parameter is for creating a file for the validation output or not.
```suggestion
* `createFile` - This parameter is a boolean flag to indicate that a validation results output is required.
```

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/README.md
> +    in the given location.
```suggestion
    If set to `true`, and the `schemaValidationOutput` parameter is set, a file holding the validation result will be created
    in the provided location.
```

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/README.md
> +    > This will hold either the respone body, or the node/property of the jsonPath as an JSON Object.
```suggestion
* `jsonResponse` - The full response from the server or the extracted node/value found using expression specified in `jsonPath` parameter as a JSON object.
    > This parameter holds the whole response body, or the node/property requested via jsonPath as a JSON object.
```

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/README.md
> +* The result of violations from the json Schema, if provided, or if the validation found none.
```suggestion
* Report of violations discovered using provided json schema, or a statement that none were found.
```

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +public class ValidateJsonUsingSchema {
Missing class summary.

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +    public String validate(String pathToSchemaFile, String pathToSaveFile,  String jsonToValidate, boolean createFile) {
Missing method summary

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +package io.testproject.addon.restfulapiclient.actions;
Missing copyright header.

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +                //Local file
```suggestion
                // Local file
```

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +            //Check if path to schema comes from a URL.
```suggestion
            // Check if schema is a URL.
```

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +                file = File.createTempFile("TempSchema", ".json");
Duplicate code - same as line 30, strings like `TempSchema` should be constants.

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +            is.close();
use `try (...)` syntax that ensures `finally` call.

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +            rawSchema = new JSONObject(new JSONTokener(is));
Why are you using `JSONObject` from org.json and not `JsonObject` from GSON?

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +                // If not defined, it will save it in the Downloads folder.
Why is it not specified in the documentation?

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +                    pathToSaveFile = String.format("%s%sDownloads%s",
Use `Path.get()` to concatenate files paths

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +                    PrintWriter writer = new PrintWriter(String.format("%s%sSchemaViolation.txt", pathToSaveFile, File.separator)
use try (...) syntax that ensures finally call.

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +                result.append("The following violations were present:\n");
```suggestion
                result.append("The following violations were present:").append(System.lineSeparator());
```

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +                    result.append(String.format("%s%s", violation, System.lineSeparator()));
```suggestion
                    result.append(violation).append(System.lineSeparator()));
```

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +            violationsAsOutput = "Failed to open schema file.";
Why aren't you using some sort of a logger like slf4j that we use all over and log the actual exception details and stack trace?

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +            violationsAsOutput = "JSON schema is invalid\nerror message is: " + e.getMessage();
```suggestion
            violationsAsOutput = "JSON schema is invalid: " + Systsem.lineSeparator() + e.getMessage();
```

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +    public static boolean isValidPath(String path) {
Could simple call `new File("/some/path").isDirectory()`

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/base/BaseAction.java
> +
Remove extra empty line.

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/base/BaseAction.java
> +        // If schema file is present , call the validation
```suggestion
        // If schema file is present, perform validation
```

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/internal/ReporterHelper.java
> +                resultStr.append(String.format("The value of {{%s}} is {{%s}}. %s", jsonPath, serverResponse.jsonParseResult, LS));
Why mixing String formatter and String builder? 
```suggestion
                resultStr.append("The value of {{").append(jsonPath).append("}}").append(" is {{").append("}}. ").append(serverResponse.jsonParseResult, LS);
```

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/internal/ReporterHelper.java
> +        if(!schemaValidationOutput.isEmpty())
It is not encouraged in Java to use IF statements without brackets { ... }

2020-09-22 13:36 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/internal/RequestHelper.java
> +                        .hostnameVerifier((s, sslSession) -> true)
Why is it still here?

2020-09-22 13:59 UTC, Rantzur1992 commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/internal/ReporterHelper.java
> +                resultStr.append(String.format("The value of {{%s}} is {{%s}}. %s", jsonPath, serverResponse.jsonParseResult, LS));
Why not?
I think it's more elegant and easy to understand.

2020-09-22 15:35 UTC, Rantzur1992 commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +            rawSchema = new JSONObject(new JSONTokener(is));
Required by the Json validation library.

2020-09-22 15:36 UTC, Rantzur1992 commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +                // If not defined, it will save it in the Downloads folder.
What are you referring too, violationsAsOutput parameter?
It is in the documentation.

2020-09-22 16:03 UTC, Rantzur1992 commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +    public static boolean isValidPath(String path) {
I don't see the reason to create a new file for that check.
Let me know what you think.

2020-09-22 17:46 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +                // If not defined, it will save it in the Downloads folder.
The fact that if the path is not provided, that it will be stored in the Downloads folder.

2020-09-22 17:59 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +    public static boolean isValidPath(String path) {
I prefer creating an instance of `File` rather than throwing and catching an exception.

2020-09-24 07:10 UTC, Rantzur1992 commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/internal/RequestHelper.java
> +                        .hostnameVerifier((s, sslSession) -> true)
Removed

2020-09-24 12:17 UTC, mstrelex requested changes

2020-09-24 12:17 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +     * @param pathToSchemaFile             - TThe path to the schema file, can be a URL/Local path to file/the JSON itself
```suggestion
     * @param pathToSchemaFile             - The path to the schema file, can be a URL/Local path to file/the JSON itself
```

2020-09-24 12:17 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +     * @param pathToSaveFile               - path to save the output file in your local system(by default will create a temp file)
```suggestion
     * @param pathToSaveFile               - path to save the output file in your local files system (by default will create a temp file)
```

2020-09-24 12:17 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +     * @param createFile                   - create a file to save the output(true/false)
```suggestion
     * @param createFile                   - create a file to save the output (true/false)
```

2020-09-24 12:17 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +
Remove extra empty line.

2020-09-24 12:17 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +
Remove extra empty line.

2020-09-24 12:17 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +
Remove extra empty line.

2020-09-24 12:17 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +
Remove extra empty line.

2020-09-24 12:17 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +                // If not defined, it will save it in the Downloads folder.
Still not in documentation.

2020-09-24 12:17 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +                    pathToSaveFile = String.format("%s%sDownloads%s",
?

2020-09-24 12:17 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +                    fileNotFoundException.getStackTrace());
```suggestion
            logger.error("Failed to open schema file", e);
```

2020-09-24 12:17 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/actions/ValidateJsonUsingSchema.java
> +            logger.debug("JSON schema is invalid, error is: {}, stacktrace: {}", e.getMessage(), e.getStackTrace());
```suggestion
            logger.debug("JSON schema is invalid: {}, e.getMessage());
```

2020-09-24 12:17 UTC, mstrelex commented on restful-api-client/src/main/java/io/testproject/addon/restfulapiclient/internal/ReporterHelper.java
> +                resultStr.append(String.format("The value of {{%s}} as JsonObject is {{%s}}. %s", jsonPath, serverResponse.jsonParseResultAsJson, LS));
Why mixing strings formatting and string builder ?
I'm fine with string.format in the case, but it should not be both.

2020-09-24 13:54 UTC, mstrelex approved these changes

2020-09-24 13:55 UTC, merged