support search fields in iOS example addon
testproject-io/addons pull request #31
Opened 2021-09-14 11:39 UTC by s-glatshtein

Several users are using the example addons as helpful actions. to help these users, we should support more types of text fields like search fields.

2021-09-30 17:02 UTC, mstrelex requested changes

2021-09-30 17:02 UTC, mstrelex commented on Examples/IOS/src/main/java/io/testproject/examples/sdk/actions/ClearFieldsAction.java
> +            for (IOSElement element : helper.getDriver().findElements(By.className("XCUIElementTypeSearchField"))) {
@s-glatshtein 

What's up with the indentation here?

2021-10-03 06:59 UTC, s-glatshtein commented on Examples/IOS/src/main/java/io/testproject/examples/sdk/actions/ClearFieldsAction.java
> +            for (IOSElement element : helper.getDriver().findElements(By.className("XCUIElementTypeSearchField"))) {
@mstrelex whoops :)

2021-10-04 12:12 UTC, mstrelex approved these changes

2021-10-04 12:12 UTC, merged